### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by antonmyrberg** [davidpaulsson/glyf#330]
There's no data to be found at the specified URL. 
Error seems to have started at February 24th according to what I have cached (last data read if I look at the news urls). 

`
Failed to load resource: the server responded with a status of 404 ()
https://davidpaulsson.se/glyf/data.json
`

**Comment by davidpaulsson** [comment]
Sorry about that! It should be up-n'-running again.
