### ISSUE TITLE
No refresh

### ISSUE THREAD

**Issue by cklouman** [davidpaulsson/glyf#405]
Hi and thanks for a great extension idea. Unfortunately in my case the news items don't refresh.. Removing and reinstalling reverts the sources back to the default but does not show any news items since last Sunday, so I assume there is a problem server side. 

![image](https://user-images.githubusercontent.com/5089369/131800370-2ae4b8be-5511-497e-bd4d-f561eccb7354.png)

**Comment by davidpaulsson** [comment]
Hi @cklouman! Thanks for letting me know, apparently Github had canceled my cron jobs that fetch articles. I've re-enabled the workflow again so new articles should start to pop up soon!
