### ISSUE TITLE
Updates are stuck on 5 May 2022

### ISSUE THREAD

**Issue by antonmyrberg** [davidpaulsson/glyf#406]
Fetch is being denied due to CORS errors. 
Using latest version of Chrome for Mac if that is of interest. 

<img width="985" alt="glyf-fetch-error" src="https://user-images.githubusercontent.com/29479737/167562874-8094eb0c-4b50-4329-a99b-10d926b7d871.png">

**Comment by davidpaulsson** [comment]
Sup @antonmyrberg! Fun to see you're using it :) I'll look at this and report back soon. Thanks!

**Comment by davidpaulsson** [comment]
I've identified the issue and cut a new patch release. Expect 1.0.7 on Google Chrome web store soon!

**Comment by antonmyrberg** [comment]
👋 😄 

It's my main news aggregator! :)
