### ISSUE TITLE
Broken in latest Chrome

### ISSUE THREAD

**Issue by antonmyrberg** [davidpaulsson/glyf#5]
Hi!
Thanks for my favorite Chrome plugin. It's broken in latest Chrome though. 
Is this something you're working on or do you want me to take a look at it? 

See the screenshot of what's going on: 
<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/29479737/50771676-94efac00-128b-11e9-89fd-b02fcc0dae4d.png">

Best, Anton

**Comment by PerMalmberg** [comment]
Yahoo retired their feeds:

> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.

As seen on https://developer.yahoo.com/weather/?guccounter=1

**Comment by davidpaulsson** [comment]
Yeah, I noticed this today. Not entirely sure how to fix it 😅

**Comment by davidpaulsson** [comment]
> Important EOL Notice: As of Thursday, Jan. 3, 2019, the YQL service at query.yahooapis.com will be retired. This will impact users of datatables.org as well as developers who creates features using this YQL service. 

> To continue using our free Yahoo Weather APIs, [yada yada weather api things] ... **Other YQL based services that use query.yahooapis.com will no longer operate.**

https://developer.yahoo.com/yql/

**Comment by davidpaulsson** [comment]
@antonmyrberg @PerMalmberg Fixed with [0.5.0](https://chrome.google.com/webstore/detail/glyf/kklidjoiedcocpkddfnknenpkpcdalnp), update available if you visit `chrome://extensions/`

**Comment by antonmyrberg** [comment]
😎👍

Den ons 9 jan. 2019 15:14 skrev David Paulsson <notifications@github.com>:

**Comment by PerMalmberg** [comment]
Thank you, I missed my daily Glyph :)
